# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: "10.x"

  - script: |
      yarn install
      yarn run build
    displayName: "yarn install"

  - script: |
      yarn run build
    displayName: "yarn validate"

  - script: |
      yarn run build
    displayName: "yarn build"

  - script: |
      yarn run deploy:preview
    displayName: "deploy preview"
    condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))

  - script: |
      yarn run deploy:preview
    displayName: "deploy prod"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
